# Generated by Django 4.2.1 on 2023-05-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
    ]
