# Generated by Django 4.2.1 on 2023-05-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productimage_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='podname',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
