# Generated by Django 4.2.1 on 2023-05-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_podname_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
