# Generated by Django 4.2.1 on 2023-05-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='podname_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='последний каталог'),
        ),
    ]
