# Generated by Django 4.1.5 on 2023-06-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Процент скидки'),
        ),
    ]
