# Generated by Django 4.1.5 on 2023-06-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_sale',
            field=models.ImageField(blank=True, null=True, upload_to='sales', verbose_name='Превью акций'),
        ),
    ]
