# Generated by Django 4.2 on 2023-06-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_image_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.attribute'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
