# Generated by Django 4.1.5 on 2023-06-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review/pictures/', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(blank=True, to='app.reviewimage'),
        ),
    ]
