# Generated by Django 4.2 on 2023-06-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_question_product_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='app.question'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='app.review'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.product'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_picture', models.ImageField(null=True, upload_to='profile_pictures/', verbose_name='Изображения продавца')),
                ('contact_info', models.CharField(max_length=100, null=True, verbose_name='Контактная информация')),
                ('notification_settings', models.BooleanField(default=True, null=True, verbose_name='Уведомления')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sellerprofile'),
        ),
    ]
