# Generated by Django 4.2 on 2023-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_product_question_alter_product_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='quest_user',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
    ]
