# Generated by Django 4.2.1 on 2023-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_cart_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_city',
            field=models.CharField(max_length=70, null=True, verbose_name='Адрес доставки (Город)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_house',
            field=models.CharField(max_length=70, null=True, verbose_name='Адрес доставки (Дом)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_kv',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Адрес доставки (Квартира)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_podezd',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Адрес доставки (Подъезд)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_street',
            field=models.CharField(max_length=70, null=True, verbose_name='Адрес доставки (Улица)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_br',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчевство'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Изображения пользователя'),
        ),
    ]
