# Generated by Django 4.2 on 2023-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
